### ISSUE TITLE
Некорректно принимает сообщения на русском

### ISSUE THREAD

**Issue by vicky-iv** [metallica127/ChatApp#1]
Шаги по воспроизведению проблемы:
1. Запустить программу
2. Подключиться к боту
3. Написать и отправить сообщение на русском.
4. Написать и отправить сообщение на английском. 

Ожидаемый результат:
После п.3 получить ответ от бота на русском, после п.4 получить ответ на английском. 

Фактический результат:
После п.3 нет ответа, после п.4 ответ нераспознанными символами и ответ на английском.

**Comment by bbl** [comment]
Баг не может быть в нашей проге, потому что мы тестировали и с ботом и другими прогами это, все было норм

**Comment by DenisSUA** [comment]
Не отображаются сообщения на русском только у человека, принимающего подключение.
