### ISSUE TITLE
Принявшая соединение программа не может отключаться, соединяться и менять ник

### ISSUE THREAD

**Issue by Jojorr** [metallica127/ChatApp#13]
Шаги для воспроизведения:
1. Открыть одну копию программы
  1.1. Ввести ник
2. Открыть вторую копию программы
  2.1. Ввести ник
3. Подключиться второй копией к первой.
4. Отключиться от первой копии из второй
Ожидаемый результат:
Активация кнопок Connect Disconnect и Change в перовой копии
Полученный результат:
Кнопки не активны

**Comment by dmytrotkk** [comment]
Проблема добавлена в список на проверку. Если она подтвердится, мы постараемся исправить её в следующем релизе.

**Comment by dmytrotkk** [comment]
Недочет исправлен в новом релизе - при приеме команды disconnect кнопки возвращаются в режим ожидания. 

``` java
if (com.getType() == Command.CommandType.DISCONNECT) {
                textArea.append("Looks like we lost him :c" + Protocol.LINE_END);
                // убить ComListThread
                connect.setEnabled(true);
                disconnect.setEnabled(false);
                send.setEnabled(false);
                apply.setEnabled(true);
            }
```
