### ISSUE TITLE
в строке Connected to: не отображается ник, написанный на русском

### ISSUE THREAD

**Issue by mgarna** [metallica127/ChatApp#3]
Шаги по воспроизведению проблемы:
1.Запустить ChatApp.
2.Авторизация(ввести ник русскими буквами , нажать "Change").
3. Ввести remote addr
4.Connect.

Ожидаемый результат:
У другого пользователя при удачном соединении в строке Connected to: отображение ника, подключившегося

Фактический результат:
Connected to: ����

**Comment by dmytrotkk** [comment]
Проблема скорее всего в кодировке, которая возникла из-за неправильно сгенерированного jar файла. В следующем релизе поправим.
