### ISSUE TITLE
Подключение к самому себе

### ISSUE THREAD

**Issue by NikitNikit** [metallica127/ChatApp#5]
Шаги по воспроизведению проблемы:
1.Запустить Chat App.
2.Ввести "127.0.0.1".
3.Нажать Connect.
Ожидаемый результат:
Подключение к самому себе.
Фактический результат:
Connected to: null

**Comment by bbl** [comment]
Так может следует ввести свой  ник для начала?

**Comment by dimalit** [comment]
Не, ну это ты слишком многого от юзера хочешь... Выводи ему сообщение!

**Comment by dmytrotkk** [comment]
Проблема исправлена. (см issues #8)
