### ISSUE TITLE
Если не ввести ник, то он так и останется пустым.

### ISSUE THREAD

**Issue by ipehov** [metallica127/ChatApp#8]
Я заметил, что если не нажимать Apply и подконнектиться, то ник установится на null, но: 

Шаги по воспроизведению проблемы:
1. Запустить ChatApp.
2. Не вводить в поле Nickname ничего и нажать Change.
3. Ввести ip и нажать Connect.

Ожидаемый результат:
Установка ника на стандартный (как я понял здесь стандартный ник - "null")

Фактический результат:
Пустой ник. Пользователь вообще без ника

**Comment by dmytrotkk** [comment]
Исправлено.
Ник по дефолту - unnamed.
